name: CI

on:
  push:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Rust format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cargo test --workspace
      - name: Build WASM
        run: cargo build --target wasm32-unknown-unknown --release
      - name: Install web deps
        working-directory: web
        run: npm ci
      - name: Lint web
        working-directory: web
        run: npm run lint
      - name: Format check web
        working-directory: web
        run: npm run format:check
      - name: Build web
        working-directory: web
        run: npm run build
      - name: Merge pull request
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: merge
