name: Deploy Web

on:
  workflow_dispatch:
  push:
    branches: [main]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write

jobs:
  deploy:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].merged == true && github.event.workflow_run.head_branch == 'main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha || github.event.workflow_run.pull_requests[0].merge_commit_sha || github.sha }}

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli

      - name: Build WASM
        working-directory: engine
        run: |
          cargo build --target wasm32-unknown-unknown --release
          wasm-bindgen --target web --out-dir pkg ../target/wasm32-unknown-unknown/release/engine.wasm

      - name: Copy assets
        run: |
          mkdir -p web/engine
          cp -r engine/pkg web/engine/pkg
          mkdir -p web/public
          cp -r fixtures web/public/fixtures

      - name: Install web deps
        working-directory: web
        run: npm ci

      - name: Build web
        working-directory: web
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./web/dist
